# Default values for action-runner.
replicaCount: 2

image:
  repository: summerwind/actions-runner
  tag: latest
  pullPolicy: IfNotPresent

runner:
  organization: ""
  repository: "kalebjorjino/infraestructura-repo"
  token: "AT2U6UKGT47IUKOBZWSPGF3KQC4GE"
  labels:
    - self-hosted
    - linux
    - k8s

serviceAccount:
  create: true
  name: action-runner-sa

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

env: []
nodeSelector: {}
tolerations: []
affinity: {}
