{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-monitoring.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
