apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/tu-organizacion/infraestructura-repo.git'
    targetRevision: HEAD
    path: platform
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
