apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "action-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "action-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "action-runner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "action-runner.serviceAccountName" . }}
      containers:
        - name: runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.runner.organization }}
            - name: RUNNER_ORG
              value: {{ .Values.runner.organization | quote }}
            {{- end }}
            {{- if .Values.runner.repository }}
            - name: RUNNER_REPO
              value: {{ .Values.runner.repository | quote }}
            {{- end }}
            - name: RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "action-runner.fullname" . }}-auth
                  key: RUNNER_TOKEN
            - name: RUNNER_LABELS
              value: {{ join "," .Values.runner.labels | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
