apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-runner.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "action-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  RUNNER_TOKEN: {{ .Values.runner.token | quote }}
